# CUSTOM REMOTE INDEX.HTML
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  dnsConfig:
    nameservers:
    - 8.8.8.8 

  volumes:
  - name: html-volume
    emptyDir: {}

  initContainers:
  - name: fetch-html
    image: curlimages/curl:latest
    command: ['sh', '-c', 'curl -o /usr/share/nginx/html/index.html https://raw.githubusercontent.com/goushaa/DEPI-Week-6-Assignment/main/index.html']
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html

  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
